config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: :task_new
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    Task.create(task_params)
    redirect_to tasks_path
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
end

private

def task_params
  params.require(:task).permit(:title, :details, :completed)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1> Edit your task</h1>

<%= form_for @task do |f| %>
  <%= f.label :title, "Update" %>
  <%= f.text_field :title %>
  <%= f.label :details, "Update your details" %>
  <%= f.text_field :details %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>



<%= link_to "Go Back", tasks_path %>

app/views/tasks/index.html.erb
<h1> All of our tasks</h1>

<ul>
  <% @tasks.each do |task|  %>
  <li style ="list-style-type: none">
    <%= check_box_tag task.id, task.title, task.completed %>

    <%= link_to task.title, task_path(task) %>
    <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, task_path(task), method: "delete",  data: {confirm: "Are you sure"} %>
  </li>
  <% end %>
</ul>

<%= link_to "Add a task", task_new_path %>

app/views/tasks/new.html.erb
<h1> Add a New Task</h1>

<%= form_for @task do |f| %>
  <%= f.label :title, "Enter a title"%>
  <%= f.text_field :title %>
  <%= f.label :details, "Enter your details" %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>


<%= link_to "Go Back", tasks_path %>

app/views/tasks/show.html.erb
<h1> <%= @task.title %></h1>


<%= link_to "Edit Task", edit_path, class: "btn btn-primary" %>

<% message_completed = @task.completed ? "This task is completed" : "This task is not completed" %>

<div class="task-details">
  <p> <%= @task.details %></p>
   <%= check_box_tag @task.id, @task.title, @task.completed %>
   <%= message_completed %>
</div>




<!-- <button type="button" class="btn btn-primary">Primary</button>

<i class="far fa-trash-alt"></i>'.html_safe
 -->